### ISSUE TITLE
2015-07-21 knajpka do wybrania

### ISSUE THREAD

**Issue by konopski** [konopski/beer-hunt#1]
Pojawily sie propozycje:
- mleczarnia
- stacja
- kontynuacja
- " knajpka na Więziennej, tam gdzie kiedyś była Pracownia"
  ta ostatnia jest o tyle ciekawa ze jeszcze tam nie bylismy, proponuje by zwiedzic

spotykamy sie o 20.00

**Comment by arroargh** [comment]
najchetniej to bym poszedl do Kontynuacji bo maja dobre piwo ale to jedyna zaleta tej knajpy. moze byc ta na Wieziennej. ja bede ok. godz. 21.

**Comment by konopski** [comment]
Łukasz R proponuje nasyp, mieszka (chyba) najdalej a ma tam dogodny dojazd

**Comment by konopski** [comment]
poniewaz niektorym to ułatwia a innym jest obojetne to oficjalnie:

```
dzis 20.00 
nasyp, stacja (nie pociag)
```

**Comment by konopski** [comment]
dziekuje, wszystkim za spotkanie
do następnego razu
