### ISSUE TITLE
2016-03-15

### ISSUE THREAD

**Issue by konopski** [konopski/beer-hunt#2]
Witam,
ponownie stajemy przed dylematem - gdzie pić by się upić. 
:beer: 
fajnie jakby był też :tea: / :coffee: / :tropical_drink:

**Comment by mzganiacz** [comment]
A wjakiej krainie mroku ty byles?
Rzeszów, Bydgoszcz?

**Comment by mzganiacz** [comment]
Jesli w tygodniu to najlepiej tournee zaczete w setce

**Comment by konopski** [comment]
Warschau

**Comment by mirmasej** [comment]
Na razie prowadzi wtorek, 15 marca.
A Ty, Marku, na doodle'u się nie wpisałeś.

**Comment by mzganiacz** [comment]
Ja mam 2 dzieci w tym jedno dwutygodniowe. Ja nie potrafie teraz planować,
wszystko na adhoku robie.
11 mar 2016 18:24 "MiR" notifications@github.com napisał(a):

**Comment by konopski** [comment]
Wtorek 15 marca, godz. 19
wpisujcie miejsca

**Comment by mirmasej** [comment]
@mzganiacz 
No to gratulacje! Tak 3maj!

@konopski 
Niestety zapomniałem, że w tym tygodniu mam w parafii rekolekcje, więc wtorek odpada i w zasadzie w tej sytuacji dołączam do grupy, co to chce się spotkać po Świętach.

**Comment by konopski** [comment]
Dzisiaj godz. 20 rynek Wrocław
Spiz?
