### ISSUE TITLE
poświąteczny wypad na piwo

### ISSUE THREAD

**Issue by konopski** [konopski/beer-hunt#3]
zapraszam wszystkich
ustalmy termin
ustalmy miejsce
enjoy

**Comment by mirmasej** [comment]
Wtorek, 5 kwietnia, 19:30, Wrocław. 
Z ustaleniem miejsca zawsze problem i zawsze kończymy w pociągu, nie wiem dlaczego, bo tam jest ciasno. Ale i tak lepszy pociąg niż bar piwny, którego właściciel unosi się honorem, gdy kupić u niego sok owocowy. Może jakiś lokal na św. Antoniego, np. cośtam 21?

**Comment by konopski** [comment]
???

**Comment by konopski** [comment]
kto to widzi?
wpisujcie miasta

**Comment by mzganiacz** [comment]
Ja widze

**Comment by arroargh** [comment]
Na Św.Antoniego jest taka knajpa Szynkarnia (https://www.facebook.com/Szynkarnia) co maja piwa rzemieslnicze. Moze tam?

**Comment by konopski** [comment]
@rabbitonweb czy jest wtedy JUG (5 kwi 2016)?
gdzie odbywa sie JUG? 
czy to daleko od szynkarni?

**Comment by konopski** [comment]
5 kwi 2016, godz 20 szynkarnia

**Comment by konopski** [comment]
reminder

**Comment by mzganiacz** [comment]
Nowego nie otwierasz?

16.02.2017 22:47 "Lukasz Konopski" <notifications@github.com> napisał(a):

**Comment by konopski** [comment]
jak bede we Wrocku to sie otworzy 🍺
